[package]
name = "rustlib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
mluau = { git = "https://github.com/mluau/mluau", features = ["send"] }
bitflags = "2.9"

[profile.release]
opt-level = "z"
panic = "unwind"
